default: &default
  adapter: postgresql
  encoding: unicode
  username: elly
  password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: paypal_payment_development

test:
  <<: *default
  database: paypal_payment_test

production:
  <<: *default
  database: paypal_payment_production
  username: paypal_payment
  password: <%= ENV["PAYPAL_PAYMENT_DATABASE_PASSWORD"] %>
